version: 2

build:
  os: "osx-14.2"
  tools:
    python: "3.9"

conda:
  environment: dosc/source/environment.yaml

# Build from the docs/source directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/source/requirements.txt
